apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "sleeping-bag-locator.fullname" . }}
  labels:
    {{- include "sleeping-bag-locator.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: main
      namespace: envoy-gateway-system
  rules:
    - matches:
        - path:
            value: /
            type: PathPrefix
      backendRefs:
        - kind: Service
          name: {{ include "sleeping-bag-locator.serviceName" . }}
          port: {{ .Values.service.port }}
          weight: 1