apiVersion: v1
kind: Service
metadata:
  name: {{ include "sleeping-bag-locator.serviceName" . }}
  labels:
    {{- include "sleeping-bag-locator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sleeping-bag-locator.selectorLabels" . | nindent 4 }}
