repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
        args:
          - --strict
          - --force-scope
          - --scopes
          - openapi,local,api,build,infra,deploy,docs,observability,test
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
        args:
          - --pattern
          - '^(?!((feature|hotfix)\/[a-zA-Z0-9\-\/]+)$).*'
