apiVersion: v2
name: sleeping-bag-locator
description: A Helm chart for sleeping-bag-locator components deployment
version: 0.1.0
home: https://github.com/ysignat/sleeping-bag-locator
kubeVersion: ~1.32.0
type: application

dependencies:
  - name: redis
    version: ~21.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

maintainers:
  - name: ysignat
    email: ignatovegors@gmail.com
    url: https://github.com/ysignat

sources:
  - https://github.com/ysignat/sleeping-bag-locator/blob/master/deploy/helm
