name: Pull request checks for infrastructure deployment
on:
  pull_request:
    branches:
      - main
    paths:
      - deploy/**
      - .github/workflows/api-pr.yml
      - .github/actions/terraform/action.yml
env:
  AWS_ACCESS_KEY: ${{ secrets.YANDEX_CLOUD_TERRAFORM_S3_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.YANDEX_CLOUD_TERRAFORM_S3_SECRET_KEY }}
  SPECS_PATH: deploy/
jobs:
  fmt:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform/
        with:
          command: fmt
          args: >-
            -check
            -diff
          version: ${{ vars.TERRAFORM_VERSION }}
          chdir: ${{ env.SPECS_PATH }}
          gh-summary-token: ${{ secrets.GITHUB_TOKEN }}
  validate:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform/
        with:
          command: validate
          args: >-
            -no-color
          version: ${{ vars.TERRAFORM_VERSION }}
          chdir: ${{ env.SPECS_PATH }}
          gh-summary-token: ${{ secrets.GITHUB_TOKEN }}
  plan:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Issue IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_CLOUD_TERRAFORM_INFRA_KEY }}
      - uses: ./.github/actions/terraform/
        env:
          YC_TOKEN: ${{ steps.issue-iam-token.outputs.token }}
        with:
          command: plan
          args: >-
            -no-color
            -input=false
          version: ${{ vars.TERRAFORM_VERSION }}
          chdir: ${{ env.SPECS_PATH }}
          gh-summary-token: ${{ secrets.GITHUB_TOKEN }}
