name: Main flow for infrastructure deployment
on:
  push:
    branches:
      - main
    paths:
      - infra/**
      - .github/workflows/infra.yml
      - .github/actions/terraform/action.yml
env:
  TERRAFORM_VERSION: ~> 1.9.5
  AWS_ACCESS_KEY: ${{ secrets.YANDEX_CLOUD_TERRAFORM_S3_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.YANDEX_CLOUD_TERRAFORM_S3_SECRET_KEY }}
  GITHUB_TOKEN: ${{ secrets.GH_TERRAFORM_TOKEN }}
  SPECS_PATH: infra/
jobs:
  plan:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Issue IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_CLOUD_TERRAFORM_INFRA_KEY }}
      - uses: ./.github/actions/terraform/
        env:
          YC_TOKEN: ${{ steps.issue-iam-token.outputs.token }}
        with:
          command: plan
          args: >-
            -no-color
            -input=false
          version: ${{ env.TERRAFORM_VERSION }}          
          chdir: ${{ env.SPECS_PATH }}  
          gh-summary-token: ${{ secrets.GITHUB_TOKEN }}
  apply:
    permissions:
      contents: read
    needs: 
      - plan
    runs-on: ubuntu-22.04
    environment: infra-review
    steps:
      - uses: actions/checkout@v4
      - name: Issue IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_CLOUD_TERRAFORM_INFRA_KEY }}
      - uses: ./.github/actions/terraform/
        env:
          YC_TOKEN: ${{ steps.issue-iam-token.outputs.token }}
        with:
          command: apply
          args: >-
            -no-color
            -input=false
            -auto-approve
          version: ${{ env.TERRAFORM_VERSION }}          
          chdir: ${{ env.SPECS_PATH }}  
          gh-summary-token: ${{ secrets.GITHUB_TOKEN }}
